dateModified: 1771924794
email:
  fromEmail: oriolnoya@gmail.com
  fromName: 'Oriol Craft Starter'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imagen:
    hasUrls: true
    name: Imagen
    settings:
      path: '@webroot/assets/uploads/imagen'
    type: craft\fs\Local
    url: '@web/assets/uploads/imagen'
meta:
  __names__:
    0a06bc5f-2e04-4a7a-8360-350090bfbfa6: Enlace # Enlace
    1a5b9fdc-1c32-4e52-a8c6-324ce30e35e1: Català # Català
    2ae9ffa4-f063-4622-9ce9-242dd916d99b: 'Fit 2000' # Fit 2000
    5a61419b-ae2d-4376-af16-96592e9cf0a2: 'Enlace i18n' # Enlace i18n
    6f7237de-98e5-487b-839a-dd78c52fa240: SEO # SEO
    8ab29f18-2345-4d26-83ee-b63fb7be6fda: 'Texto simple multi' # Texto simple multi
    8df7a5a9-0c4f-4443-a4c5-c9c2e3691239: 'Slice > Contacto' # Slice > Contacto
    37dde611-88e0-4377-ba85-8ba5c7319eee: 'Slice > Home > Masthead' # Slice > Home > Masthead
    38d0a421-6127-4344-aca0-1ff65c8b8594: Simple # Simple
    95bc1e22-93fa-49aa-999a-bfcff2fc1f3e: 'Texto simple' # Texto simple
    771cf3a5-13d3-4309-9f27-a4b6dfdc4fab: Imagen # Imagen
    918afb19-5701-4638-8acc-474aac54ca52: SEO # SEO
    8429b0f2-af63-4dc3-9b47-04ae49c3849d: 'Imágenes i18n' # Imágenes i18n
    64061d69-ee1b-46a3-9324-d5019a1394ca: Slices # Slices
    91913eed-3eac-4d98-8363-37d4a108cabb: Home # Home
    2721776a-b5ff-4590-990e-6b8a127497e8: Imágenes # Imágenes
    39235805-5257-4042-a937-b1bc04f882e7: 'Fit 1500' # Fit 1500
    72571255-ce29-40e0-a09a-06b190f79f54: Page # Page
    a58e7ac6-eeb6-4b7c-a26a-2e1f8c44f478: 'Texto rico' # Texto rico
    ab0dc730-c3fd-4174-b818-495eadb494b3: 'Fit 500' # Fit 500
    b5f0b813-586b-4599-b8ce-e8ef1b0eb355: Español # Español
    b5620131-314c-43f4-94f2-c02994402adf: Page # Page
    de3b4f14-0161-4bc8-b49f-7e7c334472e3: 'Oriol Craft Starter' # Oriol Craft Starter
    e1e105d7-b880-401b-bb44-8f6c87634b37: English # English
    fc14ea14-8531-40c0-a56d-15d19052fb34: 'Fit 1000' # Fit 1000
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  pragmatic-seo:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  pragmatic-web-toolkit:
    edition: free
    enabled: true
    schemaVersion: 1.0.0
  site-switcher:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Oriol Craft Starter'
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
