allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8c2ca9f7-82e8-4a60-bad6-85b29df858a0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-24T09:55:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 265cd191-15a3-4658-9450-fb0d34ca7f10
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-24T09:57:14+00:00'
            dismissible: false
            elementCondition: null
            style: warning
            tip: "Escoge qué pagina quieres que se muestre en la home.\r\nSi no escoges ninguna, la home se verá en blanco."
            type: craft\fieldlayoutelements\Tip
            uid: 4a95c852-42c9-4d08-9ffc-eb929e2f21e2
            userCondition: null
          -
            dateAdded: '2026-02-24T09:57:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d539bfeb-a2ba-438e-b349-6819c97b3384 # Pàgina
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f72494b-4487-4e60-8261-258863a0f4ce
            userCondition: null
            warning: null
            width: 100
        name: Contenido
        uid: 25c34fb4-0725-4855-8fe9-db1903c5fe56
        userCondition: null
    thumbFieldKey: null
handle: pageHome
hasTitleField: true
icon: null
name: 'Page > Home'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
