allowLineBreaksInTitles: true
color: null
description: null
fieldLayouts:
  0297d57b-c88b-4623-89ab-251cb4c07a86:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-02T11:02:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 60c9b288-4ade-4385-9f6f-8e494b29dd67
            userCondition: null
            warning: null
            width: 100
        name: Contenido
        uid: bc4939a5-ee60-467c-bafb-aa3c89559efd
        userCondition: null
    thumbFieldKey: null
handle: sliceContacto
hasTitleField: true
icon: null
name: 'Slice > Contacto'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
