allowLineBreaksInTitles: true
color: null
description: null
fieldLayouts:
  d284e8fc-cfa7-4561-890d-ab097b40a074:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-02T11:01:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2520892b-8a1f-4659-80cc-cca1c5a8f51e
            userCondition: null
            warning: null
            width: 100
        name: Contenido
        uid: 636294f7-fff9-4033-a3d9-09137d8081cc
        userCondition: null
    thumbFieldKey: null
handle: sliceHomeMasthead
hasTitleField: true
icon: null
name: 'Slice > Home > Masthead'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
