columnSuffix: null
handle: imagenes
instructions: null
name: Im√°genes
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:771cf3a5-13d3-4309-9f27-a4b6dfdc4fab' # Imagen
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: thumbs
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:771cf3a5-13d3-4309-9f27-a4b6dfdc4fab' # Imagen
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:771cf3a5-13d3-4309-9f27-a4b6dfdc4fab' # Imagen
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
