columnSuffix: null
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  defaultDescription: ''
  defaultImageDescription: ''
  defaultImageId: null
  defaultTitle: ''
  translationMethod: site
translationKeyFormat: null
translationMethod: site
type: pragmatic\webtoolkit\domains\seo\fields\SeoField
