altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  314feda6-9309-46ba-bcfb-3e305d20a8d7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-02T10:36:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 60b5df50-1fcf-4bb8-add2-10bfe65545e0
            userCondition: null
            warning: null
            width: 50
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2026-02-02T10:37:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: a483ff8a-398f-4044-ac31-0297af629720
            userCondition: null
            warning: null
            width: 50
        name: Contenido
        uid: db97b217-e014-42c9-8e4f-8b1d95e3fe43
        userCondition: null
    thumbFieldKey: null
fs: imagen
handle: imagen
name: Imagen
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
